#!/bin/bash
# ============================================================
# LAR System — Sync .env to Azure App Service Application Settings
#
# Reads a local .env file and applies every variable as an Azure
# App Service Application Setting across all five LAR Web Apps.
# Credentials are sent via the Azure CLI (az) — never through
# environment variables visible in process listings.
#
# Usage:
#   chmod +x scripts/azure-appsettings-sync.sh
#   ./scripts/azure-appsettings-sync.sh
#   ./scripts/azure-appsettings-sync.sh --env-file .env.staging
#   ./scripts/azure-appsettings-sync.sh --app lar-b2c
#   ./scripts/azure-appsettings-sync.sh --resource-group rg-prod --dry-run
#
# Options:
#   --env-file FILE        Path to .env file (default: .env in repo root)
#   --resource-group RG    Azure Resource Group (default: rg-lar-system)
#   --app APP_NAME         Apply to a single app only (default: all five)
#   --slot SLOT            Deployment slot (default: Production)
#   --dry-run              Print what would be set without applying changes
#   -h, --help             Show this help
#
# Prerequisites:
#   - Azure CLI installed and logged in (az login)
#   - Contributor access to the resource group
#   - .env file generated by scripts/setup-env.sh
#
# How it works:
#   All variables from .env are applied to every Web App EXCEPT:
#     DB_DATABASE / DB2_DATABASE — each app uses its own database name,
#     so these are mapped per-app (see the APP_DATABASE_MAP below).
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ---- Defaults ------------------------------------------------
ENV_FILE="${REPO_ROOT}/.env"
RESOURCE_GROUP="rg-lar-system"
SLOT="Production"
DRY_RUN=false
ONLY_APP=""

# ---- All five LAR Web Apps -----------------------------------
ALL_APPS=(lar-b2c lar-agent lar-supplier lar-supervision lar-services)

# Per-app primary database names (DB_DATABASE).
# If DB_DATABASE is set in .env, this map overrides it per app so that
# each module connects to its own database on the shared MySQL server.
declare -A APP_DATABASE_MAP=(
  [lar-b2c]="lar_b2c"
  [lar-agent]="lar_agent"
  [lar-supplier]="lar_supplier"
  [lar-supervision]="lar_supervision"
  [lar-services]="lar_webservices"
)

# ---- Colours -------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
die()     { error "$*"; exit 1; }

# ---- Parse arguments -----------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)       ENV_FILE="$2";        shift 2 ;;
    --resource-group) RESOURCE_GROUP="$2";  shift 2 ;;
    --app)            ONLY_APP="$2";        shift 2 ;;
    --slot)           SLOT="$2";            shift 2 ;;
    --dry-run)        DRY_RUN=true;         shift ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//' | sed '1{/^!/d}'
      exit 0 ;;
    *) die "Unknown option: $1. Use --help for usage." ;;
  esac
done

# ---- Validate prerequisites ----------------------------------
[[ -f "$ENV_FILE" ]] || die ".env file not found at '${ENV_FILE}'. Run scripts/setup-env.sh first."

if ! command -v az &>/dev/null; then
  die "Azure CLI (az) not found. Install from https://aka.ms/installazurecli"
fi

if ! az account show &>/dev/null; then
  die "Not logged in to Azure. Run: az login"
fi

# ---- Parse .env into an associative array -------------------
declare -A ENV_VARS

while IFS= read -r line || [[ -n "$line" ]]; do
  # Skip blank lines and comments
  [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
  # Skip lines without =
  [[ "$line" != *=* ]] && continue

  key="${line%%=*}"
  value="${line#*=}"

  # Strip surrounding matching quotes (only outer single or double quotes)
  if [[ "$value" =~ ^\'(.*)\'$ ]]; then
    value="${BASH_REMATCH[1]}"
  elif [[ "$value" =~ ^\"(.*)\"$ ]]; then
    value="${BASH_REMATCH[1]}"
  fi

  ENV_VARS["$key"]="$value"
done < "$ENV_FILE"

[[ ${#ENV_VARS[@]} -eq 0 ]] && die "No variables found in ${ENV_FILE}. Is the file empty?"

# ---- Determine target apps -----------------------------------
if [[ -n "$ONLY_APP" ]]; then
  APPS=("$ONLY_APP")
else
  APPS=("${ALL_APPS[@]}")
fi

# ---- Banner --------------------------------------------------
echo ""
echo -e "${BOLD}${CYAN}========================================================"
echo "  LAR System — Azure App Settings Sync"
echo "========================================================${RESET}"
echo ""
echo "  Resource Group : ${RESOURCE_GROUP}"
echo "  Env file       : ${ENV_FILE}"
echo "  Apps           : ${APPS[*]}"
echo "  Dry run        : ${DRY_RUN}"
echo ""

# ---- Check Azure CLI is authenticated with the right sub -----
SUBSCRIPTION=$(az account show --query name -o tsv 2>/dev/null || echo "unknown")
info "Azure subscription: ${SUBSCRIPTION}"
echo ""

# ---- Sync function -------------------------------------------
sync_app() {
  local app_name="$1"

  info "Syncing settings to: ${BOLD}${app_name}${RESET}"

  # Verify the app exists
  if ! az webapp show \
    --resource-group "$RESOURCE_GROUP" \
    --name "$app_name" \
    --query name -o tsv &>/dev/null; then
    warn "App '${app_name}' not found in resource group '${RESOURCE_GROUP}' — skipping."
    return 0
  fi

  # Build the settings array
  # az webapp config appsettings set accepts: KEY1=VALUE1 KEY2=VALUE2 ...
  local -a SETTINGS=()

  for key in "${!ENV_VARS[@]}"; do
    local value="${ENV_VARS[$key]}"

    # Skip vars that map differently per app
    [[ "$key" == "DB_DATABASE" || "$key" == "DB2_DATABASE" ]] && continue

    SETTINGS+=("${key}=${value}")
  done

  # APP_ENV → also set as ENVIRONMENT for CodeIgniter
  if [[ -n "${ENV_VARS[APP_ENV]:-}" ]]; then
    SETTINGS+=("ENVIRONMENT=${ENV_VARS[APP_ENV]}")
  fi

  # Per-app database name override
  if [[ -n "${APP_DATABASE_MAP[$app_name]+x}" ]]; then
    SETTINGS+=("DB_DATABASE=${APP_DATABASE_MAP[$app_name]}")
  fi

  # DB2_DATABASE: use the value from .env unless the app has a specific one
  if [[ -n "${ENV_VARS[DB2_DATABASE]:-}" ]]; then
    SETTINGS+=("DB2_DATABASE=${ENV_VARS[DB2_DATABASE]}")
  fi

  # Add Azure App Service standard settings
  SETTINGS+=("WEBSITE_RUN_FROM_PACKAGE=1")
  SETTINGS+=("PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/home/site/ini")

  if ${DRY_RUN}; then
    echo "  [DRY-RUN] Would apply ${#SETTINGS[@]} settings to '${app_name}':"
    for s in "${SETTINGS[@]}"; do
      KEY="${s%%=*}"
      # Mask secret values
      if echo "$KEY" | grep -qiE "password|secret|salt|key|token"; then
        echo "    ${KEY}=***"
      else
        echo "    ${s}"
      fi
    done
    return 0
  fi

  # Apply settings one at a time to avoid command-line length limits and
  # to prevent special characters in values from breaking argument parsing.
  for setting in "${SETTINGS[@]}"; do
    setting_key="${setting%%=*}"
    setting_value="${setting#*=}"
    az webapp config appsettings set \
      --resource-group "$RESOURCE_GROUP" \
      --name "$app_name" \
      --settings "${setting_key}=${setting_value}" \
      --output none
  done

  success "Settings applied to '${app_name}' (${#SETTINGS[@]} settings)."
}

# ---- Run sync for each app -----------------------------------
ERRORS=0
for APP_NAME in "${APPS[@]}"; do
  sync_app "$APP_NAME" || ERRORS=$((ERRORS + 1))
  echo ""
done

# ---- Restart apps so new settings take effect ---------------
if ! ${DRY_RUN} && [[ ${ERRORS} -eq 0 ]]; then
  echo ""
  info "Restarting apps to apply new settings..."
  for APP_NAME in "${APPS[@]}"; do
    if az webapp show \
      --resource-group "$RESOURCE_GROUP" \
      --name "$APP_NAME" \
      --query name -o tsv &>/dev/null; then
      az webapp restart \
        --resource-group "$RESOURCE_GROUP" \
        --name "$APP_NAME" \
        --output none
      success "Restarted: ${APP_NAME}"
    fi
  done
fi

echo ""
if [[ ${ERRORS} -eq 0 ]]; then
  success "All apps synced successfully."
  if ! ${DRY_RUN}; then
    echo ""
    echo "  Verify the settings in the Azure portal:"
    echo "  https://portal.azure.com/#browse/Microsoft.Web%2Fsites"
  fi
else
  error "${ERRORS} app(s) failed. Review the output above."
  exit 1
fi
